import SearchContextProvider from "@/context/SearchContextProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Torre Test App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#27292d] flex flex-col items-center">
        <SearchContextProvider>{children}</SearchContextProvider>
      </body>
    </html>
  );
}
